config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'weather#index'

  get '/zipcode', to: 'weather#zipcode'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  before_action :fetch_location_params, only: [:index, :zipcode]

  def index
    if @lat_long
      load_weather_and_forecast(lat_long: @lat_long)
    else
      flash[:alert] = "Geolocation data is missing."
      redirect_to root_path
    end
  end

  def zipcode
    if @zipcode
      load_weather_and_forecast(zipcode: @zipcode)
    else
      flash[:alert] = "Zipcode is required."
      redirect_to root_path
    end
  end

  private

  def fetch_location_params
    @lat_long = params[:lat_long]&.split("|") if params[:lat_long].present?
    @zipcode = params[:zipcode] if params[:zipcode].present?
  end

  def load_weather_and_forecast(options = {})
    @weather_output = WeatherQueryService.new(options).call
    @forecast_output = fetch_cached_forecast(options) || ForecastQueryService.new(options).call
  end

  def fetch_cached_forecast(options)
    if options[:zipcode]
      cache_key = options[:zipcode]
      Rails.cache.fetch(cache_key, expires_in: 1.hour) do
        ForecastQueryService.new(zipcode: cache_key).call
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather Wonderer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <div class="container-fluid">
      <%= render 'shared/error' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_current_weather.html.erb
<div id="current-weather" class="card text-center">
  <div class="card-header">
    Today's weather in <span class="city"><%= current_weather['name'] %>, <%= current_weather['sys']['country'] %></span> | <span class="date"><%= Time.at(current_weather['dt']).to_formatted_s(:long) %></span>
  </div>
  <div class="card-body">
    <h5 class="card-title">  <%= image_tag "http://openweathermap.org/img/w/" + (current_weather['weather'][0]['icon']).html_safe + ".png" %> <%= current_weather['main']['temp'] %> °F,  <%= current_weather['weather'][0]['main']%></h5>
    <p class="card-text"><span class="description"><%= current_weather['weather'][0]['description']%> | </span><span class="high">High: <%= current_weather['main']['temp_max'] %> °F</span> | <span class="high">Low: <%= current_weather['main']['temp_min'] %> °F</span></p>
  </div>
  <div class="card-footer">
    <span class="pressure">Pressure: <%= current_weather['main']['pressure']%> hpa</span> | <span class="pressure"> Humidity: <%= current_weather['main']['humidity']%> %</span> | <span class="sunrise"> Sunrise: <%= Time.at(current_weather['sys']['sunrise']).to_formatted_s(:long) %></span> | <span class="sunset"> Sunset: <%= Time.at(current_weather['sys']['sunset']).to_formatted_s(:long) %></span>
  </div>
</div>

app/views/shared/_error.html.erb
<% error_message ||= '' %>

<div id="error-message" class="alert alert-danger <%= error_message.present? ? 'show' : 'hide' %>" role="alert"><%= error_message %></div>

app/views/shared/_forecast.html.erb
<% if caching_enabled %>
  <h1>Caching for forecast is enabled for the 6 next consecutive 3 hour intervals</h1>
<%end%>
<div id="forecast" class="card-columns">
  <% forecast['list'].each do |forecast| %>
    <div class="card h-100">
      <div class="card-header">
        <span class="date"><%= Time.at(forecast['dt']).strftime("%B %e, %Y, at %I:%M %p" ) %></span>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= image_tag "http://openweathermap.org/img/w/" + (forecast['weather'][0]['icon']).html_safe + ".png" %> <%= forecast['main']['temp'] %> °F,  <%= forecast['weather'][0]['main']%></h5>
        <p class="card-text"><span class="description"><%= forecast['weather'][0]['description']%> | </span><span class="high">High: <%= forecast['main']['temp_max'] %> °F</span> | <span class="high">Low: <%= forecast['main']['temp_min'] %> °F</span></p>
      </div>
      <div class="card-footer">
        <small class="text-muted">
          <span class="pressure">Pressure: <%= forecast['main']['pressure']%> hpa</span> | <span class="pressure"> Humidity: <%= forecast['main']['humidity']%> %</span>
        </small>
      </div>
    </div>
  <%end%>
</div>

app/views/shared/_header.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container text-center">
    <a class="nav-link" href="/"><h1 class="display-4">Weather forecast by zipcode</h1></a>
    <%= form_tag zipcode_path, class: 'col-lg-6 offset-lg-3', method: :get do  %>
      <div class="row justify-content-center">
        <%= text_field_tag 'zipcode', params[:zipcode], placeholder: 'Please enter a 5 digit zip code', id: "zipcode", class: "form-control mr-sm-2" %>
        <%= submit_tag 'Search', class: "btn btn-outline-secondary my-2 my-sm-0" %>
      </div>
    <% end %>
  </div>
</div>

app/views/weather/index.html.erb
<% if @lat_lang.present? %>
  <%= render partial: 'shared/current_weather', locals: { current_weather: @weather_output } %>
  <%= render partial: 'shared/zipcode', locals: { forecast: @forecast_output } %>
<% else %>
  <script>
      getLocation();
  </script>
<% end %>

app/views/weather/zipcode.html.erb
<% if params[:zipcode].blank? %>
  <%= render partial: 'shared/error', locals: { error_message: 'please enter a valid 5-digit zipcode'.capitalize } %>
<% elsif @weather_output['message'].present? %>
  <%= render partial: 'shared/error', locals: { error_message: @weather_output['message'].capitalize } %>
<% else %>
  <%= render partial: 'shared/current_weather', locals: { current_weather: @weather_output } %>
  <%= render partial: 'shared/forecast', locals: { caching_enabled: @using_cached_forecast, forecast: @forecast_output } %>
<% end %>